OData implementation
Acumatica/AcumaticaRESTAPIClientForCSharp pull request #17
Opened 2022-07-14 10:10 UTC by alaraalara

1. Added a get method in OData.cs that handles both login and data retrievals. 
2. Added a ODataExample.cs file to demonstrate the login and data retrievals in both OData version 3 and 4.
3. Console Application solution uses dll files generated by RestClient as a reference, instead of Nuget packages.

2022-07-14 18:16 UTC, Dmitrii-Naumov requested changes
see comments in the code

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
>      public class ODataAPI : BaseApi
If we use "RestRequest" for sending the API call, does it make sense to have it derived from BaseApi?

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
> +        public string Get(string version, string resource = null, Dictionary<string, string> parameters = null, string username = null, string password = null)
Ideally the OData call must work with both OAuth authentication and base authentication. In the this implementation only base is possible, right?

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
> +                basePath += "/" + version;
I don't like the version being string parameter. It leaves a lot of room for a human error. It'd be better that only correct values can be passed to the method

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
> +                        request.AddParameter(parameter.Key, parameter.Value);
As for parameters, it looks like in this implementation a developer needs to pass proper strings as parameters. 
However, it'd be better if the method signature makes it clear what parameters are available and eliminates a chance of passing incorrect parameters

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
> +                basePath += "/" + version;
Having basePath as global variable but modifying it in the method body is a bad pattern. If you call this method twice, the basePath becomes invalid

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
> +                client = new RestClient(basePath);
For Odata request with multitenant environment the url is not correct here. We need companyID part in the url

2022-07-14 18:16 UTC, Dmitrii-Naumov commented on Acumatica REST API Console Application/ODataExample.cs
> +			parameter.Add("format", "json");
I think we should always just use json for Odata, no need to pass it from where you invoke the method

2022-07-20 13:03 UTC, alaraalara reviewed
1. added compatibility with Oauth. 
2. Parameters are now shown in method signature. 
3. Version is converted to an enum variable. 
4. Configurepath method is added for allowing multitenant environment. 
5. Json format is default for Get method.

2022-08-19 14:59 UTC, Dmitrii-Naumov requested changes

2022-08-19 14:59 UTC, Dmitrii-Naumov commented on Acumatica.RESTClient/BaseApi/ODataAPI.cs
> +    public enum Version
Let's rename it to ODataVersion

2022-08-19 14:59 UTC, Dmitrii-Naumov commented on Acumatica REST API Console Application/Program.cs
> +		const string tokenUrl = "https://localhost/MyStoreInstance/identity/connect/token";
It seems like this constant is never used. 
Please remove it

2022-08-25 18:54 UTC, merged